# Install: Manage basic resource setup, such as packages or service users.

---

- name: "Setup | Install | Default | Remove unwanted packages (e.g., to prevent conflicts or resolve incompatibilities)"
  ansible.builtin.package:
    name: "{{ __run_sshd_packages_removal }}"
    state: "absent"
  when:
    - __run_sshd_packages_removal is ansible.builtin.defined
    - (__run_sshd_packages_removal | ansible.builtin.length) > 0


- name: "Setup | Install | Default | Install or upgrade packages"
  ansible.builtin.package:
    name: "{{ __run_sshd_packages_install }}"
    state: "{{ 'latest' if run_sshd_autoupgrade else 'present' }}"
  when:
    - __run_sshd_packages_install is ansible.builtin.defined
    - (__run_sshd_packages_install | ansible.builtin.length) > 0


- name: "Setup | Install | Default | Remove unwanted files and directories (e.g., to prevent conflicts or resolve incompatibilities)"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  when:
    - __run_sshd_paths_removal is ansible.builtin.defined
    - (__run_sshd_paths_removal | ansible.builtin.length) > 0
  loop: "{{ __run_sshd_paths_removal }}"


- name: "Setup | Install | Default | Neutralize distribution config files (overwrite to survive package updates)"
  ansible.builtin.copy:
    dest: "{{ item['key'] }}"
    content: |
      {{ item['value'] }} Managed by Ansible (foundata.sshd.run)
      {{ item['value'] }}
      {{ item['value'] }} Content intentionally cleared. The original distribution file conflicted
      {{ item['value'] }} with configuration managed by the foundata.sshd.run role.
      {{ item['value'] }}
      {{ item['value'] }} To restore the original file content, reinstall the owning package:
      {% if (ansible_facts['os_family'] | ansible.builtin.lower) == 'debian' %}
      {{ item['value'] }}   dpkg -S '{{ item['key'] }}'"  # find the package that owns this file
      {{ item['value'] }}   apt-get install --reinstall <package>  # reinstall it to restore the original
      {% elif (ansible_facts['os_family'] | ansible.builtin.lower) == 'suse' %}
      {{ item['value'] }}   rpm -qf '{{ item['key'] }}'  # find the package that owns this file
      {{ item['value'] }}   zypper install --force <package>  # reinstall it to restore the original
      {% elif (ansible_facts['os_family'] | ansible.builtin.lower) == 'redhat' %}
      {{ item['value'] }}   rpm -qf '{{ item['key'] }}'  # find the package that owns this file
      {{ item['value'] }}   dnf reinstall <package>  # reinstall it to restore the original
      {% else %}
      {{ item['value'] }}   Use your package manager to find the owning package and reinstall it.
      {% endif %}
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r" # 0644
  when:
    - __run_sshd_paths_neutralize is ansible.builtin.defined
    - (__run_sshd_paths_neutralize | ansible.builtin.length) > 0
  loop: "{{ __run_sshd_paths_neutralize | ansible.builtin.dict2items }}"
  loop_control:
    label: "{{ item['key'] }}"


- name: "Setup | Install | Default | Ensure privilege separation directory exists with proper permissions"
  ansible.builtin.file:
    path: "{{ __run_sshd_privseparation_dir_path }}"
    state: "directory"
    owner: "{{ __run_sshd_privseparation_dir_owner }}"
    group: "{{ __run_sshd_privseparation_dir_group }}"
    mode: "{{ __run_sshd_privseparation_dir_mode }}"
  when:
    - __run_sshd_privseparation_dir_path is ansible.builtin.defined
    - __run_sshd_privseparation_dir_path | ansible.builtin.length > 0
