# Tasks for the Molecule prepare stage: Add resources needed for later steps
# (e.g. verify) on all driver-created instances.

- name: "Molecule | Prepare | Install packages needed for pip"
  ansible.builtin.package:
    name:
      - "python3-packaging"
      - "python3-pip"
    state: "present"


# For openSUSE Leap 15: Install required packages for all available Python
# versions. This prevents "ModuleNotFoundError: No module named 'packaging'"
# errors regardless of which Python interpreter is selected by Ansible.
- name: "Molecule | Prepare | Install packages needed for pip (openSUSE Leap 15)"
  ansible.builtin.package:
    name:
      - "python311-packaging"
      - "python311-pip"
      - "python312-packaging"
      - "python312-pip"
    state: "present"
  when:
    - ansible_facts is defined
    - ansible_facts['distribution'] is defined
    - ansible_facts['distribution_major_version'] is defined
    - (ansible_facts['distribution'] | lower) == 'opensuse leap'
    - (ansible_facts['distribution_major_version'] | int) == 15


- name: "Molecule | Prepare | Install ssh-audit"
  ansible.builtin.pip:
    name:
      - "ssh-audit"
    state: "present"
    break_system_packages: true
