# Tasks for the Molecule converge stage: Execute the collection role "run"
# against all driver-created instances.

- name: "Molecule | Converge | Include the foundata.sshd.run role"
  ansible.builtin.include_role:
    name: "foundata.sshd.run"
  vars:
    run_sshd_state: "present"
    run_sshd_sshd_settings:
      PermitRootLogin: true # Insecure, just for testing purposes
      PermitEmptyPasswords: true # Insecure, just for testing purposes
      PasswordAuthentication: true # Insecure, just for testing purposes
