# Role argument validation.
#
# See defaults/main.yml for details on each variable. For more information on
# the argument_specs.yml format, refer to the official Ansible documentation:
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation

---

argument_specs:

  # foundata.sshd/roles/run/tasks/main.yml entry point
  main:
    short_description: "Main entry point for the foundata.sshd.run role"
    options:

      run_sshd_state:
        type: "str"
        required: true
        choices:
          - "present"
          - "absent"

      run_sshd_autoupgrade:
        type: "bool"
        required: true

      run_sshd_service_state:
        type: "str"
        required: true
        choices:
          - "enabled"
          - "disabled"
          - "running"
          - "unmanaged"

      run_sshd_sshd_settings:
        type: "dict"
        required: true
