# Execute the collection role "run" against all driver-created instances (cleanup / absent)

- name: "Molecule | Cleanup | Include the foundata.sshd.run role"
  ansible.builtin.include_role:
    name: "foundata.sshd.run"
  vars:
    run_fail2ban_state: "absent"
